name: Verify
on: [push]
jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Verify
        run: sh verify.sh
